baseURL = 'https://adamrehman.dev'
title = 'Portfolio - Adam Rehman'
theme = 'ananke'

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 10

[languages.en]
contentDir = "content/en"
languageCode = 'en-US'
weight = 1
title = "Data Science and Machine Learning Portfolio"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
mainSections = ["post"]
text_color = ""
author = "Adam Rehman"
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
background_color_class = "bg-black"
featured_image_class = "cover bg-top"
cover_dimming_class = "bg-black-60"
recent_posts_number = 10

[params.ananke]
show_recent_posts = true  # Ensure posts show on homepage

[params.ananke.social.share]
networks = ["email", "linkedin", "github"]  # Fixed typo: "network" to "networks"

[params.ananke.social.follow]  # Fixed typo: "param" to "params"
networks = ["linkedin", "github"]

[params.ananke.social.linkedin]
username = "adam-rehman"

[params.ananke.social.github]
username = "AdamRehmanML"

# [[menu.main]]
#name = "Projects"
#url = "/post/"
# weight = 1
